import {
  extract,
  transform,
  load,
  dataQualityCheck,
  dataQualityCheckConfig,
  dataProfiling,
  dataProfilingConfig,
  insightExtract,
  insightLoad,
  loggingOptions,
  loggingOptionsConfig,
  stateStoreTypeMapping,
  sourceAlignedDataProductExtract,
  aggregatedDataProductExtract,
  consumptionReadyDataProductExtract,
  sourceExtract,
  stateManagement,
  datasetsPipelines,
  ingestionPipelines,
  streaming,
} from './config/componentConfig';

export const config = {
  extract,
  transform,
  load,
  dataQualityCheck,
  dataQualityCheckConfig,
  dataProfiling,
  dataProfilingConfig,
  insightExtract,
  insightLoad,
  loggingOptions,
  loggingOptionsConfig,
  stateStoreTypeMapping,
  sourceAlignedDataProductExtract,
  aggregatedDataProductExtract,
  consumptionReadyDataProductExtract,
  sourceExtract,
  stateManagement,
  datasetsPipelines,
  ingestionPipelines,
  streaming,
};
