import {
  extract,
  transform,
  load,
  dataQualityCheck,
  dataQualityCheckConfig,
  dataProfiling,
  dataProfilingConfig,
  insightExtract,
  insightLoad,
  loggingOptions,
  loggingOptionsConfig,
  stateStoreTypeMapping,
  curatedExtract,
  aggregatedExtract,
  sourceExtract,
} from './config/componentConfig';

export const config = {
  extract,
  transform,
  load,
  dataQualityCheck,
  dataQualityCheckConfig,
  dataProfiling,
  dataProfilingConfig,
  insightExtract,
  insightLoad,
  loggingOptions,
  loggingOptionsConfig,
  stateStoreTypeMapping,
  curatedExtract,
  aggregatedExtract,
  sourceExtract,
};
